version: '3.8'

services:
  db:
    image: mysql:8.0  # ใช้ image ของ MySQL เวอร์ชัน 8.0
    container_name: leave_management_db_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password  # << เปลี่ยนเป็นรหัสผ่านที่คาดเดายาก
      MYSQL_DATABASE: leave_management_db             # ชื่อฐานข้อมูลที่ Docker จะสร้างให้
      MYSQL_USER: app_user                            # << สร้าง user ใหม่สำหรับแอปพลิเคชัน
      MYSQL_PASSWORD: your_app_password               # << ตั้งรหัสผ่านสำหรับ user ใหม่
    ports:
      - "3306:3306"  # Map พอร์ต 3306 ของเครื่องเราไปยังพอร์ต 3306 ใน container
    volumes:
      - db-data:/var/lib/mysql  # เก็บข้อมูลของ database ไว้ที่ volume ชื่อ db-data เพื่อไม่ให้ข้อมูลหาย
      - ./docker/leave_management_db.sql:/docker-entrypoint-leave_management_dbdb.d/leave_management_db.sql # นำไฟล์ init.sql ของเราเข้าไปใน container
volumes:
  db-data: